[package]

name = "conduit-mime-types"
version = "0.5.1"
authors = ["wycats@gmail.com"]
license = "MIT"
description = "MIME type definitions for conduit"
repository = "https://github.com/conduit-rust/mime-types"
